### PR TITLE
Refine summarizer

### PR DESCRIPTION
**Pull request by onmyway133**
- Update destination with id and without id
- Show available destinations, this is used to auto select a working destination
- Refine summarizer, so it tracks task duration and error
- Filter process handler

Screenshot 2019-12-23 at 09 07 10

And merry christmas 🎄

### CODE REVIEW

**Comment by onmyway133** [comment]
@thii Is there any way we can detect error in xcodebuild log via xcbeautify ?

**Comment by thii** [comment]
Warning and error outputs are printed out as is.

**Comment by onmyway133** [comment]
@thii ja, if there's way to validate error output, that  would mean a lot to our Puma tool

**Comment by thii** [comment]
What do you mean by "validate error output"? `clang` and `swiftc`'s warnings and errors follow the same format so maybe you can parse that:

file_path:row:column: warning: warning_message
file_path:row:column: error: error_message

For example (copied from Clang documentation):
```
format-strings.c:91:13: warning: '.*' specified field precision is missing a matching 'int' argument
  printf("%.*d");
              ^
```

**Comment by onmyway133** [comment]
@thii Never mind, I use a sync queue in Process so all errors should be catched

**Pull request merged**
